# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: "http://mcdon.xyz
url: "http://mcdon.xyz"
name: Gavin McDonnell
job: Infrastructure Engineer
location: West Midlands, UK
languages: HTML, CSS and Javascript
twitter_username: gavin_mcdonnell
github_username:  gavin-mcdonnell
# codepen_username:  mattcouchman
email_address: gavin@mcdon.xyz

# Build settings
markdown: kramdown
